language: node_js
node_js:
- '8'
branches:
  only:
  - develop
cache:
  directories:
  - node_modules
before_install:
- openssl aes-256-cbc -K $encrypted_8b9bbf37c6f3_key -iv $encrypted_8b9bbf37c6f3_iv
  -in .travis/github.enc -out ~/.ssh/github -d
- chmod 600 ~/.ssh/github
- eval $(ssh-agent)
- ssh-add ~/.ssh/github
- cp .travis/ssh_config ~/.ssh/config
- git config --global user.name "FX-Max"
- git config --global user.email "812234333@qq.com"
install:
- npm install -g hexo
- npm install -g hexo-cli
- npm install hexo --save
- npm install
script:
- hexo clean
- hexo g

after_success:
- hexo deploy
